##########################
### Analysis Countries ###
##########################

iso_codes:
# - "AGO"
# - "ALB"
- "ARG" # mem
# - "ARM"
# - "BDI"
# - "BEN"
# - "BFA"
# - "BGD"
# - "BGR"
# - "BIH"
# - "BLZ"
# - "BOL"
# - "BRA" # mem
# - "BTN"
# - "BWA"
# - "CAF"
# - "CIV"
# - "CMR"
- "COD" # mem
# - "COG"
# - "COL"
# - "CRI"
# - "DJI"
# - "DOM"
- "DZA" # mem
# - "ECU"
# - "EGY"
# - "ERI"
# - "ETH"
# - "GEO"
# - "GHA"
# - "GIN"
# - "GMB"
# - "GNB"
# - "GTM"
# - "GUY"
# - "HND"
# - "HTI"
- "IDN" # mem
# - "IND" # mem
# - "JAM"
# - "JOR"
# - "KAZ"
# - "KEN"
# - "KGZ"
# - "KHM"
# - "LAO"
# - "LBR"
# - "LKA"
# - "LSO"
# - "MAR"
# - "MDA"
# - "MDG"
- "MEX" # mem
# - "MKD"
# - "MLI"
# - "MNE"
# - "MOZ"
# - "MRT"
# - "MWI"
# - "MYS"
# - "NER"
# - "NGA"
# - "NIC"
# - "NPL"
# - "PAK"
# - "PER"
# - "PHL"
# - "PRY"
# - "ROU"
# - "RWA"
# - "SEN"
# - "SLE"
# - "SLV"
# - "SRB"
# - "SUR"
# - "SWZ"
# - "TCD"
# - "TGO"
# - "THA"
# - "TJK"
# - "TKM"
# - "TUN"
# - "TUR"
# - "TZA"
# - "UGA"
# - "UKR"
# - "UZB"
# - "VNM"
# - "ZAF"
# - "ZMB"
# - "ZWE"